
version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - VITE_API_URL=http://localhost/api

  backend:
    build:
      context: ./backend-dotnet
      dockerfile: Dockerfile
    depends_on:
      - db
    networks:
      - app-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=db;Port=3306;Database=feelcalm;User=dbuser;Password=dbpassword;
      - JWT__Secret=${JWT_SECRET}
      - JWT__ExpiryInDays=1

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=feelcalm
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpassword

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
