
version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - VITE_API_URL=http://localhost/api

  backend:
    build:
      context: ./backend-dotnet
      dockerfile: Dockerfile
    networks:
      - app-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=localhost;Port=3306;Database=feelcalm;User=root;Password=root;
      - JWT__Secret=${JWT_SECRET}
      - JWT__ExpiryInDays=1

networks:
  app-network:
    driver: bridge
